name: repfiles_firestore
description: A Flutter application for managing reptile collections, breeding projects, schedules, and inventory.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  # UI & Charts
  fl_chart: ^1.0.0
  qr_flutter: ^4.1.0
  
  # Image handling
  image_picker: ^1.1.2
  
  # State management & utilities
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 